/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#8392a6",
        "secondary-fixed-dim": "#2fd9f4",
        "outline": "#908fa0",
        "error-container": "#93000a",
        "tertiary": "#b9c8de",
        "surface-container-high": "#292932",
        "on-primary-container": "#0d0096",
        "surface-dim": "#13131b",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary": "#1000a9",
        "surface": "#13131b",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-surface": "#e4e1ed",
        "tertiary-fixed-dim": "#b9c8de",
        "secondary": "#5de6ff",
        "on-tertiary-fixed": "#0d1c2d",
        "tertiary-fixed": "#d4e4fa",
        "surface-bright": "#393841",
        "on-secondary": "#00363e",
        "on-tertiary-fixed-variant": "#39485a",
        "on-secondary-fixed-variant": "#004e5a",
        "on-surface": "#e4e1ed",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-container": "#1c2b3c",
        "on-surface-variant": "#c7c4d7",
        "on-error": "#690005",
        "on-background": "#e4e1ed",
        "on-error-container": "#ffdad6",
        "surface-tint": "#c0c1ff",
        "surface-container-low": "#1b1b23",
        "on-primary-fixed": "#07006c",
        "on-secondary-fixed": "#001f25",
        "on-tertiary": "#233143",
        "on-secondary-container": "#00515d",
        "primary": "#c0c1ff",
        "outline-variant": "#464554",
        "surface-container-highest": "#34343d",
        "surface-container": "#1f1f27",
        "secondary-container": "#00cbe6",
        "error": "#ffb4ab",
        "primary-container": "#8083ff",
        "secondary-fixed": "#a2eeff",
        "surface-container-lowest": "#0d0d15",
        "inverse-primary": "#494bd6",
        "inverse-on-surface": "#303038",
        "background": "#13131b",
        "surface-variant": "#34343d"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "xs": "4px",
        "xl": "32px",
        "md": "16px",
        "panel-gutter": "1px",
        "lg": "24px",
        "sm": "8px",
        "unit": "4px"
      },
      "fontFamily": {
        "code-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "title-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "code-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-base": ["14px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["11px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "title-sm": ["18px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-sm": ["13px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
